version: '3'

services:
  db:
    image: postgres:11
  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - 80:8000