version: '3'

services:
  redis:
    image: redis:5-buster
  db:
    image: postgres:11
  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    ports:
      - 80:8000
  celery:
    environment:
        - DJANGO_SETTINGS_MODULE=challenge.settings.dev
    image: challenge_backend
    command: celery -A challenge worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    environment:
      - DJANGO_SETTINGS_MODULE=challenge.settings.dev
    image: challenge_backend
    command: celery -A challenge beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis